sudo: required

language: c

services:
    - docker

script:
    - docker build --rm -t linkit-smart .
    # bootloader
    - docker run -it linkit-smart /bin/bash
    - cd /linkit-smart-uboot
    - make
    # build firmware
    - docker run -it linkit-smart /bin/bash
    - cd /openwrt
    - ./scripts/feeds update && ./scripts/feeds install -a
    - make menuconfig
    - make V=99

notifications:
    email: false
